name: 03 nodejs build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 ## Clona project

      - name: Use Node.js 20.x ## Descarga la versión 20 de nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies ## Instala las dependencias de nodejs
        run: npm ci
        working-directory: project_nodejs ## Accede al proyecto para ajecutar los comandos

      - name: Run tests ## Correr test de nodejs
        run: npm test
        working-directory: project_nodejs ## Accede al proyecto para ajecutar los comandos
